# /Users/fw-skylerlemay/.config/tmuxinator/AdminPortal.yml

name: AdminPortal
root: ~/code/AdminPortal

windows:
  - editor:
      layout: main-vertical
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - nvim
        - 
  - server: npm run dev
