# /Users/skyler.lemay/.config/tmuxinator/blog.yml

name: blog
root: ~/code/skyler-lemay-blog

windows:
  - editor:
      layout: main-vertical
      panes:
        - nvim
        - hugo serve
        - 
