# /Users/skyler.lemay/.config/tmuxinator/code.yml

name: code
root: <%= @settings["workspace"] ||= '~/' %>

windows:
  - editor:
      layout: main-vertical
      panes:
        - nvim
        -
        -
  - server:
