# /Users/fw-skylerlemay/.config/tmuxinator/StudentPortal.yml

name: StudentPortal
root: ~/code/StudentPortal

windows:
  - editor:
      layout: main-vertical
      panes:
        - nvim
        - 
  - server: docker compose pull; make up
