prSections:
- title: My Pull Requests
  filters: >-
    is:open
    author:@me
- title: Involved
  filters: >-
    owner:JoinFreeWorld
    is:open
    draft:false
    involves:@me
    -author:@me
- title: Review Requested
  filters: >-
    owner:JoinFreeWorld
    is:open
    draft:false
    review-requested:@me
    -author:mend-for-github-com[bot]
- title: Renovate
  filters: >-
    owner:JoinFreeWorld
    is:open
    draft:false
    author:mend-for-github-com[bot]
    ENO
defaults:
  preview:
    open: true
    width: 75
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths:
  JoinFreeWorld/*: ~/code/*
smartFilteringAtLaunch: false
theme:
  ui:
    table:
      showSeparator: true
pager:
  diff: ""
